"use client";

import { useState, useEffect, useRef, useCallback, useTransition } from "react";
import { runSynthesis } from "./actions/synthesize";
import type { Brief } from "@/lib/synthesize";

function toMarkdown(brief: Brief): string {
  let md = `# Lumen Brief\n\n`;
  md += `**Generated:** ${new Date(brief.createdAt).toLocaleString()}\n`;
  md += `**Confidence:** ${brief.confidence}%\n\n`;
  md += `## Summary\n${brief.summary}\n\n`;

  if (brief.claims.length) {
    md += `## Key Claims\n`;
    brief.claims.forEach((c, i) => {
      md += `${i + 1}. ${c.text}\n`;
      if (c.contradictedBy?.length) md += `   *⚠ Flagged for possible contradiction*\n`;
    });
    md += `\n`;
  }

  if (brief.contradictions.length) {
    md += `## Contradiction Flags\n`;
    brief.contradictions.forEach((x) => {
      md += `- **Tension:** ${x.note}\n`;
      md += `  - A: ${x.claimA}\n`;
      md += `  - B: ${x.claimB}\n`;
    });
    md += `\n`;
  }

  md += `## Sources\n`;
  brief.sources.forEach((s) => {
    md += `- **${s.title}** (reliability ${s.reliability}%)${s.fetched === false ? " — fetch failed" : ""}\n`;
    if (s.url) md += `  ${s.url}\n`;
    md += `  > ${s.excerpt}\n`;
  });

  if (brief.processingNotes?.length) {
    md += `\n## Processing Notes\n`;
    brief.processingNotes.forEach((n) => (md += `- ${n}\n`));
  }

  md += `\n---\n*Generated by Lumen — Personal Knowledge Synthesizer*\n`;
  return md;
}

export default function LumenPage() {
  const [input, setInput] = useState("");
  const [brief, setBrief] = useState<Brief | null>(null);
  const [history, setHistory] = useState<Brief[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [showHistory, setShowHistory] = useState(false);
  const [isPending, startTransition] = useTransition();
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    try {
      const raw = localStorage.getItem("lumen-history-v2");
      if (raw) setHistory(JSON.parse(raw));
    } catch {}
  }, []);

  useEffect(() => {
    try {
      localStorage.setItem("lumen-history-v2", JSON.stringify(history.slice(0, 25)));
    } catch {}
  }, [history]);

  const runSynthesize = useCallback(() => {
    if (!input.trim() || isPending) return;
    setError(null);
    setBrief(null);

    startTransition(async () => {
      const result = await runSynthesis(input);
      if ("error" in result) {
        setError(result.error);
        return;
      }
      setBrief(result);
      setHistory((prev) => [result, ...prev.filter((h) => h.id !== result.id)].slice(0, 25));
    });
  }, [input, isPending]);

  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === "Enter") {
        e.preventDefault();
        runSynthesize();
      }
      if (e.key === "Escape") setShowHistory(false);
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [runSynthesize]);

  const copyMarkdown = () => {
    if (!brief) return;
    navigator.clipboard.writeText(toMarkdown(brief)).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    });
  };

  const downloadMarkdown = () => {
    if (!brief) return;
    const blob = new Blob([toMarkdown(brief)], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `lumen-brief-${brief.id}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const loadDemo = () => {
    setInput(
      `Recent observations on large language model reasoning capabilities:\n\nhttps://openai.com/index/learning-to-reason-with-llms/\nhttps://arxiv.org/abs/2501.12948\n\nThe ability to perform multi-step reasoning appears to improve significantly with scale and reinforcement learning techniques. However, independent evaluations sometimes report higher error rates on out-of-distribution problems than the original papers claim. Local note: potential test-set contamination remains a concern that is hard to fully audit without deeper access.`
    );
    textareaRef.current?.focus();
  };

  const clearAll = () => {
    setInput("");
    setBrief(null);
    setError(null);
    textareaRef.current?.focus();
  };

  return (
    <div className="min-h-screen flex flex-col">
      <header className="border-b border-zinc-800/80 bg-zinc-950/90 backdrop-blur sticky top-0 z-30">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 h-14 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-7 h-7 rounded-md bg-blue-600 flex items-center justify-center text-sm font-bold tracking-tight shadow-lg shadow-blue-600/20">
              L
            </div>
            <div>
              <span className="font-semibold tracking-tight text-zinc-100">Lumen</span>
              <span className="hidden sm:inline text-xs text-zinc-500 font-medium ml-2">
                Knowledge Synthesizer
              </span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => setShowHistory((v) => !v)}
              className="text-xs px-3 py-1.5 rounded-md border border-zinc-700 hover:bg-zinc-800 text-zinc-300 transition"
            >
              History ({history.length})
            </button>
            <button
              onClick={loadDemo}
              className="text-xs px-3 py-1.5 rounded-md border border-zinc-700 hover:bg-zinc-800 text-zinc-300 transition"
            >
              Load demo
            </button>
          </div>
        </div>
      </header>

      <main className="flex-1 max-w-5xl w-full mx-auto px-4 sm:px-6 py-8 flex flex-col gap-6">
        <section className="rounded-xl border border-zinc-800 bg-zinc-900/40 overflow-hidden shadow-xl shadow-black/20">
          <div className="px-4 py-3 border-b border-zinc-800 flex items-center justify-between">
            <h2 className="text-sm font-medium text-zinc-300">
              Input — links, notes, or raw thoughts
            </h2>
            <span className="text-[11px] text-zinc-500 font-mono">
              ⌘ / Ctrl + Enter
            </span>
          </div>
          <textarea
            ref={textareaRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Paste one or more URLs + your notes…\n\nExample:\nhttps://example.com/paper\nKey claim from the meeting: the effect size was larger than expected."
            className="w-full min-h-[200px] bg-transparent px-4 py-3 text-sm text-zinc-100 placeholder:text-zinc-600 resize-y focus:outline-none font-mono leading-relaxed"
            spellCheck={false}
            disabled={isPending}
          />
          <div className="px-4 py-3 border-t border-zinc-800 flex items-center justify-between gap-3">
            <button
              onClick={clearAll}
              disabled={isPending}
              className="text-xs text-zinc-500 hover:text-zinc-300 transition disabled:opacity-40"
            >
              Clear
            </button>
            <button
              onClick={runSynthesize}
              disabled={!input.trim() || isPending}
              className="inline-flex items-center gap-2 px-5 py-2 rounded-lg bg-blue-600 hover:bg-blue-500 disabled:opacity-40 disabled:cursor-not-allowed text-sm font-medium transition shadow-lg shadow-blue-600/20"
            >
              {isPending ? (
                <>
                  <span className="w-3.5 h-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  Fetching & synthesizing…
                </>
              ) : (
                "Synthesize"
              )}
            </button>
          </div>
        </section>

        {error && (
          <div className="rounded-xl border border-red-500/40 bg-red-500/10 px-5 py-4 text-sm text-red-200">
            {error}
          </div>
        )}

        {isPending && (
          <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-8 text-center">
            <div className="inline-flex items-center gap-3 text-zinc-400 text-sm">
              <span className="w-4 h-4 border-2 border-zinc-600 border-t-blue-500 rounded-full animate-spin" />
              Retrieving content from links and extracting claims…
            </div>
            <p className="text-xs text-zinc-600 mt-3">
              This may take a few seconds depending on the sources.
            </p>
          </div>
        )}

        {brief && !isPending && (
          <section className="animate-fade-in space-y-5">
            <div className="flex flex-wrap items-center gap-3 justify-between">
              <div className="flex items-center gap-3">
                <h2 className="text-lg font-semibold text-zinc-100">Brief</h2>
                <span
                  className={`text-xs px-2.5 py-0.5 rounded-full font-medium ${
                    brief.confidence >= 75
                      ? "bg-emerald-500/15 text-emerald-400"
                      : brief.confidence >= 55
                      ? "bg-amber-500/15 text-amber-400"
                      : "bg-red-500/15 text-red-400"
                  }`}
                >
                  Confidence {brief.confidence}%
                </span>
              </div>
              <div className="flex items-center gap-2">
                <button
                  onClick={copyMarkdown}
                  className="text-xs px-3 py-1.5 rounded-md border border-zinc-700 hover:bg-zinc-800 text-zinc-300 transition"
                >
                  {copied ? "Copied ✓" : "Copy Markdown"}
                </button>
                <button
                  onClick={downloadMarkdown}
                  className="text-xs px-3 py-1.5 rounded-md border border-zinc-700 hover:bg-zinc-800 text-zinc-300 transition"
                >
                  Download .md
                </button>
                <button
                  onClick={() => window.print()}
                  className="text-xs px-3 py-1.5 rounded-md border border-zinc-700 hover:bg-zinc-800 text-zinc-300 transition"
                >
                  Print / PDF
                </button>
              </div>
            </div>

            <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-5">
              <h3 className="text-xs uppercase tracking-wider text-zinc-500 mb-2">Summary</h3>
              <p className="text-sm text-zinc-200 leading-relaxed">{brief.summary}</p>
            </div>

            <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-5">
              <h3 className="text-xs uppercase tracking-wider text-zinc-500 mb-3">Key Claims</h3>
              <ul className="space-y-3">
                {brief.claims.map((c, i) => (
                  <li key={c.id} className="flex gap-3">
                    <span className="text-xs font-mono text-zinc-500 mt-0.5 shrink-0">{i + 1}.</span>
                    <div>
                      <p className="text-sm text-zinc-200 leading-relaxed">{c.text}</p>
                      {c.contradictedBy && c.contradictedBy.length > 0 && (
                        <p className="text-xs text-amber-400/90 mt-1.5 flex items-center gap-1.5">
                          <span>⚠</span> Contradiction flag raised
                        </p>
                      )}
                    </div>
                  </li>
                ))}
              </ul>
            </div>

            {brief.contradictions.length > 0 && (
              <div className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-5">
                <h3 className="text-xs uppercase tracking-wider text-amber-400/80 mb-3">
                  Contradiction Flags
                </h3>
                {brief.contradictions.map((x, i) => (
                  <div key={i} className="text-sm text-zinc-300 space-y-1.5">
                    <p className="text-amber-200/90">{x.note}</p>
                    <p className="text-xs text-zinc-500 pl-3 border-l border-zinc-700">A: {x.claimA}</p>
                    <p className="text-xs text-zinc-500 pl-3 border-l border-zinc-700">B: {x.claimB}</p>
                  </div>
                ))}
              </div>
            )}

            <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-5">
              <h3 className="text-xs uppercase tracking-wider text-zinc-500 mb-3">
                Sources & Reliability
              </h3>
              <ul className="space-y-5">
                {brief.sources.map((s) => (
                  <li key={s.id} className="flex flex-col sm:flex-row sm:items-start gap-2 sm:gap-4">
                    <div className="flex items-center gap-2 min-w-[160px]">
                      <div
                        className={`w-2 h-2 rounded-full shrink-0 ${
                          s.reliability >= 75
                            ? "bg-emerald-400"
                            : s.reliability >= 55
                            ? "bg-amber-400"
                            : "bg-red-400"
                        }`}
                      />
                      <span className="text-sm font-medium text-zinc-200 truncate">{s.title}</span>
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1.5">
                        <div className="h-1.5 flex-1 max-w-[140px] bg-zinc-800 rounded-full overflow-hidden">
                          <div
                            className="h-full bg-blue-500 rounded-full transition-all"
                            style={{ width: `${s.reliability}%` }}
                          />
                        </div>
                        <span className="text-xs text-zinc-500 font-mono">{s.reliability}%</span>
                        {s.fetched === false && (
                          <span className="text-[10px] text-red-400/80 uppercase tracking-wide">failed</span>
                        )}
                      </div>
                      {s.url && (
                        <a
                          href={s.url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-xs text-blue-400 hover:underline break-all"
                        >
                          {s.url}
                        </a>
                      )}
                      <p className="text-xs text-zinc-500 mt-1.5 leading-relaxed">{s.excerpt}</p>
                    </div>
                  </li>
                ))}
              </ul>
            </div>

            {brief.processingNotes && brief.processingNotes.length > 0 && (
              <div className="rounded-xl border border-zinc-800/60 bg-zinc-900/30 px-5 py-3">
                <h3 className="text-[11px] uppercase tracking-wider text-zinc-600 mb-1.5">
                  Processing log
                </h3>
                <ul className="text-xs text-zinc-500 space-y-0.5">
                  {brief.processingNotes.map((n, i) => (
                    <li key={i}>• {n}</li>
                  ))}
                </ul>
              </div>
            )}
          </section>
        )}

        {!brief && !isPending && !error && (
          <div className="flex-1 flex items-center justify-center py-20 text-center">
            <div className="max-w-md space-y-4">
              <p className="text-zinc-500 text-sm leading-relaxed">
                Paste links and notes above, then press{" "}
                <kbd className="px-1.5 py-0.5 rounded bg-zinc-800 text-zinc-300 text-xs font-mono">
                  ⌘ + Enter
                </kbd>{" "}
                to fetch content and generate a grounded brief.
              </p>
              <p className="text-zinc-600 text-xs">
                Real URL fetching · Claim extraction · Reliability scoring · Local history
              </p>
            </div>
          </div>
        )}
      </main>

      {showHistory && (
        <div className="fixed inset-0 z-40 flex justify-end">
          <div className="absolute inset-0 bg-black/60" onClick={() => setShowHistory(false)} />
          <aside className="relative w-full max-w-sm bg-zinc-900 border-l border-zinc-800 h-full overflow-y-auto animate-fade-in shadow-2xl">
            <div className="p-4 border-b border-zinc-800 flex items-center justify-between sticky top-0 bg-zinc-900 z-10">
              <h3 className="font-medium text-sm">Recent briefs</h3>
              <button
                onClick={() => setShowHistory(false)}
                className="text-zinc-500 hover:text-zinc-300 text-sm"
              >
                Close
              </button>
            </div>
            {history.length === 0 ? (
              <p className="p-4 text-sm text-zinc-500">No history yet.</p>
            ) : (
              <ul className="divide-y divide-zinc-800">
                {history.map((h) => (
                  <li key={h.id}>
                    <button
                      onClick={() => {
                        setBrief(h);
                        setShowHistory(false);
                      }}
                      className="w-full text-left px-4 py-3.5 hover:bg-zinc-800/60 transition"
                    >
                      <p className="text-sm text-zinc-200 line-clamp-2 leading-snug">
                        {h.query || "Untitled"}
                      </p>
                      <p className="text-xs text-zinc-500 mt-1.5">
                        {new Date(h.createdAt).toLocaleString()} · {h.confidence}% confidence
                      </p>
                    </button>
                  </li>
                ))}
              </ul>
            )}
          </aside>
        </div>
      )}

      <footer className="border-t border-zinc-800/60 py-4 text-center text-[11px] text-zinc-600">
        Lumen · Real fetching · Grounded claims · Built for clarity
      </footer>
    </div>
  );
}
